name: レポートフォーム
description: 不具合や改善をレポート
labels: ["triage"]
body:
  - type: checkboxes
    id: issue-type
    attributes:
      label: レポートの種類を選択してください
      multiple: true
      options:
        - label: A,動作の問題
        - label: B,UIの問題
        - label: C,設計の問題
        - label: D,その他
  - type: textarea
    id: what-happened
    attributes:
      label: 見つかった現象・動作
      description: 再現手順があればそれも記載お願いします
    validations:
      required: true
  - type: input
    id: txn
    attributes:
      label: 事象が発生したTxn Hash
      description: 原因調査のため出来るだけ記入してください。
      placeholder: 0x....
  - type: dropdown
    id: browsers
    attributes:
      label: Webブラウザ
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
   - type: input
    id: web3client
    attributes:
      label: Web3インタフェース
      placeholder: MetaMask
